package com.universign.universigncs.oed.domain.enumeration;

/**
 * The CheckStatus enumeration.
 */
public enum CheckStatus {
    PERFECT, EMAIL_AND_PHONE_IN_OTHER_ORGANISATION, EMAIL_FOUND, EMAIL_FOUND_BUT_PHONE_USED, EMAIL_FOUND_IN_OTHER_ORGANIZATION, EMAIL_FOUND_IN_OTHER_ORGANIZATION_BUT_PHONE_USED, PHONE_FOUND, PHONE_FOUND_IN_OTHER_ORGANIZATION, NOT_FOUND, EMAIL_INVALID, PHONE_INVALID
}
