export const enum CheckStatus {
  PERFECT = 'PERFECT',

  EMAIL_AND_PHONE_IN_OTHER_ORGANISATION = 'EMAIL_AND_PHONE_IN_OTHER_ORGANISATION',

  EMAIL_FOUND = 'EMAIL_FOUND',

  EMAIL_FOUND_BUT_PHONE_USED = 'EMAIL_FOUND_BUT_PHONE_USED',

  EMAIL_FOUND_IN_OTHER_ORGANIZATION = 'EMAIL_FOUND_IN_OTHER_ORGANIZATION',

  EMAIL_FOUND_IN_OTHER_ORGANIZATION_BUT_PHONE_USED = 'EMAIL_FOUND_IN_OTHER_ORGANIZATION_BUT_PHONE_USED',

  PHONE_FOUND = 'PHONE_FOUND',

  PHONE_FOUND_IN_OTHER_ORGANIZATION = 'PHONE_FOUND_IN_OTHER_ORGANIZATION',

  NOT_FOUND = 'NOT_FOUND',

  EMAIL_INVALID = 'EMAIL_INVALID',

  PHONE_INVALID = 'PHONE_INVALID',
}
